### ISSUE TITLE
Only works on main screen

### ISSUE THREAD

**Issue by benvd** [ifrins/Snappr#1]
It only seems to change the wallpaper of the main screen, not of any external screens.

**Comment by uxDaniel** [comment]
+1

**Comment by ifrins** [comment]
I'm working on a 2.0 update, and one of the main "features" will be support for changing the wallpaper of all screens and all spaces.

**Comment by uxDaniel** [comment]
Awesome! Thanks a lot @ifrins!

**Comment by ifrins** [comment]
This was fixed in release 1.1.1. 🎉
